### ISSUE TITLE
Flash error with ESP32-S3: Timeout

### ISSUE THREAD

**Issue by walchko** [espressif/esptool-js#47]
Appears to be the same with S2 and C3 ... there is a timeout error when trying to flash the chip.

```
esptool.js v0.1-dev
Serial port WebSerial VendorID 0x303a ProductID 0x1001
Connecting....
Detecting chip type... ESP32-S3
Chip is ESP32-S3
Features: Wi-Fi,BLE
Crystal is 40MHz
MAC: f4:12:fa:44:1b:fc
Uploading stub...
Running stub...
Stub running...
Changing baudrate to 460800
Changed
Erasing flash (this may take a while)...
Chip erase completed successfully in 1.082s
Compressed 4420676 bytes to 124923...
Writing at 0x0... (12%)
Writing at 0x4000... (25%)
Writing at 0x8000... (37%)
Error: Timeout
```

**Comment by adetauriac** [comment]
Hello

I ve the same error :-( no idea to fix it

**Comment by nicpottier** [comment]
Same problem here using this board:
  https://www.lilygo.cc/products/t-display-s3

**Comment by igrr** [comment]
> Serial port WebSerial VendorID 0x303a ProductID 0x1001

Looks like you are flashing it via USB_SERIAL_JTAG. This should work after #54 and #65.

**Comment by igrr** [comment]
Both related PRs have been merged, I think this should be fixed now. Please reopen if the issue still exists.

**Comment by makermelissa** [comment]
It looks like this is still an issue. I am trying to flash an ESP32-S3 and still getting a timeout error:
<img width="635" alt="Screen Shot 2023-01-26 at 10 37 11 AM" src="https://user-images.githubusercontent.com/2681417/214922056-6489c254-7390-4c95-bce2-fd21ab49601d.png">

I'm trying to flash the combined.bin inside of https://github.com/adafruit/tinyuf2/releases/download/0.12.0/tinyuf2-adafruit_feather_esp32s3_tft-0.12.0.zip at address 0, which works fine on https://adafruit.github.io/Adafruit_WebSerial_ESPTool/. However, I'd love to retire that tool in favor of this one once it is reliable enough.

**Comment by makermelissa** [comment]
The board I'm testing with is https://www.adafruit.com/product/5483. However, there's a number of bootloaders for espboards at https://github.com/adafruit/tinyuf2/releases if you want to test with a similar one.

**Comment by makermelissa** [comment]
#83 looks kind of promising for fixing the issue though.

**Comment by igrr** [comment]
@makermelissa I have tried the PR #83 with the binary linked tinyuf2 binary and flashing was successful. I've pushed this branch also to https://igrr.github.io/esptool-js/ for you to try.

**Comment by makermelissa** [comment]
Ok, I just tried it and it worked great. Thank you. It looks like this tool is getting very close now.

**Comment by MichaelDu9226** [comment]
@igrr The timeout problem still seems to exist on ESP32 S3 USB JTAG/DEBUG mode.
I have tested https://igrr.github.io/esptool-js/ and https://espressif.github.io/esptool-js/.
![image](https://user-images.githubusercontent.com/25977780/222328323-cd113408-4672-4411-aa65-629a5fe9089e.png)

![image](https://user-images.githubusercontent.com/25977780/222328205-520a5ba7-2638-4151-93ba-759ec4bb6b1e.png)

**Comment by curlyz** [comment]
> @igrr The timeout problem still seems to exist on ESP32 S3 USB JTAG/DEBUG mode. I have tested https://igrr.github.io/esptool-js/ and https://espressif.github.io/esptool-js/. ![image](https://user-images.githubusercontent.com/25977780/222328323-cd113408-4672-4411-aa65-629a5fe9089e.png)
> 
> ![image](https://user-images.githubusercontent.com/25977780/222328205-520a5ba7-2638-4151-93ba-759ec4bb6b1e.png)

Confirm this issue is also existing on C3, esptool-js keep timeout although python version work, but with --no-stub flag onl
